### ISSUE TITLE
Need help translating the bot in a lot of languages

### ISSUE THREAD

**Issue by Zenrac** [Zenrac/watora-translations#11]
Need help to finish the translation in 
```
- German 
- Spanish  
```

Other language are gladly accepted

**Comment by Zenrac** [comment]
- French (100%)
- English (100%)
- German (35%)
- Spanish  (25%)

**Comment by santteegt** [comment]
I'm working on the Spanish translation

**Comment by muelletr** [comment]
Hello, I can help you with the german translation.

**Comment by Zenrac** [comment]
@muelletr It would be cool ! Check out [german.json](https://github.com/Zenrac/watora-translations/blob/master/i18n/german.json)

**Comment by Zenrac** [comment]
Almost done, and closing because of duplicate
