### ISSUE TITLE
Translate 6 lines for new commands 

### ISSUE THREAD

**Issue by Zenrac** [Zenrac/watora-translations#112]
Translate 6 lines (645 to 650) to : 
- Arabic 
- Chinese 
- ~~German~~
- Indonesian
- Italian
- Korean
- ~~Polish~~
- ~~Portuguese~~
- ~~Russian~~
- ~~Spanish~~
- Turkish

Translations are [here](https://github.com/Zenrac/watora-translations/tree/master/i18n) if you want to help.

**Comment by giantpanpan** [comment]
@Zenrac Hi can I work on Chinese translation for line 645 to 650

**Comment by Zenrac** [comment]
@giantpanpan Sure, don't need to ask if you can ! Everyone can contribute to any translation. :+1:

**Comment by nSedrickm** [comment]
Hi. What is the criteria for doing the translation.Should one speak the language natively or leverage google translate?

**Comment by Zenrac** [comment]
@nSedrickm Hi, no google translations pls :) For more informations see [README.md](https://github.com/Zenrac/watora-translations/blob/master/README.md)

**Comment by Zenrac** [comment]
Not every translations done but I think we can close this.
