### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by Zenrac** [Zenrac/watora-translations#22]
Finish the translation of [spanish.json](https://github.com/Zenrac/watora-translations/blob/master/i18n/spanish.json)

**Comment by wolframtheta** [comment]
I'll do the translation to spanish and if you want to catalan too

**Comment by wolframtheta** [comment]
No problem @Zenrac... it's easy and I like to do this :D

**Comment by Jorege98** [comment]
I'll do translation too, starting from now if you want ^^

**Comment by MauricioLanda** [comment]
i'll finish spanish translation today

**Comment by Zenrac** [comment]
Would be much appreciated

**Comment by MauricioLanda** [comment]
i just finished it right now

**Comment by MauricioLanda** [comment]
it's finished now

**Comment by Zenrac** [comment]
Thanks again

**Comment by MauricioLanda** [comment]
No problem
