### ISSUE TITLE
Translate 1 line to Italian

### ISSUE THREAD

**Issue by Zenrac** [Zenrac/watora-translations#55]
Hi, I need help to translate https://github.com/Zenrac/watora-translations/blob/c134f52bef66fc6726e301aba98564800818c5f9/i18n/italian.json#L435 (the end of the line) to Italian can someone help ? 

`A role called DJ is giving DJ permissions by default`

**Comment by soulspark666** [comment]
I am on it.

**Comment by Zenrac** [comment]
Can someone check the PR ?

**Comment by Zenrac** [comment]
#56 closes this
